name: deploy-github-actions
run-name: ğŸŒ ${{ github.actor }} is running deploy to PRODUCTION
on: 
  workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test-github-actions.yml


  build-deploy:
    name: ğŸŒğŸš€ğŸŒ– Build and deploy
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: âš™ï¸ Install deps
        run: npm ci
    
      - name: ğŸ¬ Build application
        run: npm run build
        
        if: success()
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 30
        
      - name: Deploy to GitHub Pages
        id: deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i gh-pages
          npx gh-pages -d . -u "github-actions-bot <support+actions@github.com>"
