name: build-github-actions
run-name: ğŸ‹ï¸â€â™‚ï¸ ${{ github.actor }} is running build

on:
  push:
    branches: 
    - master
    - release-v\d+
  workflow_call:

jobs:
  call-commitlint-workflow:
    uses: ./.github/workflows/commitlint-github-actions.yml

  call-test-workflow:
    uses: ./.github/workflows/test-github-actions.yml

  build:
    name: ğŸ¬ Build application
    needs: call-test-workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: âš™ï¸ Install deps
        run: npm ci
    
      - name: ğŸ§³ Build App
        run: npm run build
      
        if: success()
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 30  