name: Test a new pull request
run-name: "Test a new pull request by @${{ github.actor }}"
on: [pull_request]
jobs:
  test:
    name: ğŸ§ª Perform the pull request's testing
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: ğŸªœ Checkout
        uses: actions/checkout@v3
      - name: ğŸ”§ Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: ğŸ“¥ Install the NPM dependencies
        run: npm ci
      - name: ğŸ§ª Run the tests
        uses: ./.github/actions/run-tests
      - name: â›“ï¸ Add the run's link to the pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ğŸ‰ All tests has succeeded. The results are published on https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}.
      
